#!/usr/bin/env bash
set -e

pip uninstall -y spikeinterface
git clone https://github.com/alejoe91/spikeinterface.git
cd spikeinterface
git checkout 6cfdffdbaeadeb743665b0dcd289c29782374baa
pip install --no-cache-dir .
cd ..