#!/usr/bin/env bash
set -e

git clone https://github.com/SpikeInterface/spikeinterface.git
cd spikeinterface
git checkout 73f4d58d2d542e607155d49d30716cc28215e12f
pip install --no-cache-dir .[full]
cd ..
